# Generated by Django 5.2 on 2026-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_customuser_lockinuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockinuser',
            name='username',
        ),
        migrations.AddField(
            model_name='lockinuser',
            name='lockin_activities',
            field=models.CharField(default='Empty', max_length=128),
        ),
        migrations.AddField(
            model_name='lockinuser',
            name='user_photo',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='lockinuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
