# Generated by Django 5.2 on 2026-03-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_lockinuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockinuser',
            name='user_photo',
        ),
    ]
