# Generated by Django 5.2 on 2026-03-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_lockinuser_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockinuser',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
