# Generated by Django 5.2 on 2026-03-26 02:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_lockinuser_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockinuser',
            name='lockin_activities',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.CreateModel(
            name='LockinActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=128)),
                ('activity_duration', models.DateField(default=datetime.date.today)),
                ('activity_description', models.CharField(blank=True, max_length=256)),
                ('activity_start_date', models.DateField(default=datetime.date.today)),
                ('activity_completion_reward', models.CharField(blank=True, max_length=128)),
                ('activity_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LockinActivityNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateField(unique=True)),
                ('note_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lockinactivity')),
            ],
        ),
    ]
