# Generated by Django 5.2 on 2026-04-04 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_lockinuser_lockin_activities_lockinactivity_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lockinuser',
            managers=[
            ],
        ),
    ]
