# Generated by Django 5.2 on 2026-04-04 23:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_lockinuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lockinuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
