# Generated by Django 5.2 on 2026-04-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_lockinuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lockinuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='lockinuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lockinuser',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
