# Generated by Django 5.2 on 2026-06-23 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_lockinuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lockinactivity',
            old_name='activity_username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lockinactivitynotes',
            old_name='note_activity_id',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='lockinactivity',
            name='activity_duration',
        ),
        migrations.RemoveField(
            model_name='lockinuser',
            name='lockin_activities',
        ),
        migrations.AddField(
            model_name='lockinactivity',
            name='activity_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lockinactivitynotes',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lockinuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterUniqueTogether(
            name='lockinactivitynotes',
            unique_together={('activity', 'created_at')},
        ),
    ]
